<p>Tra i nostri obiettivi vi è la costruzione di una Rete libera e di proprietà dei cittadini. Il modello è semplice: ogni partecipante si connette ai suoi vicini per mezzo di un <i>nodo</i> che a loro volta si connette ai rispettivi vicini, creando così una rete di computer di tipo comunitario.<br />È possibile vedere la lista dei nodi connessi attraverso il nostro <a href=\"http://map.ninux.org\" target=\"_blank\" title=\"Richiede inoltro ad Internet\">Mapserver</a>.</p>
<p>Una rete di questo tipo è di proprietà dei cittadini perché ogni partecipante è proprietario e responsabile del proprio nodo. In questa maniera non vi è bisogno di nessun <acronym title=\"Internet Service Provider\">ISP</acronym>, abbonamento mensile, contratto né registrazione. Semplicemente, una volta connessi si è nella Rete.</p>
<p>A differenza delle normali <acronym title=\"Asymmetric Digital Subscriber Line\">ADSL</acronym>, la cui capacità di upload è spesso limitata e differisce di molto ripetto a quella in download, i nostri collegamenti sono di tipo simmetrico (tanto in download quanto in upload).</p>
<p>Una volta in Rete è possibile usufruire e fornire allo stesso tempo alcuni <a href=\"http://wiki.ninux.org/Servizi\" target=\"_blank\" title=\"Richiede inoltro ad Internet\">servizi</a> quali la telefonia <acronym title=\"Voice over IP\">VoIP</acronym>, lo scambio di contenuti (che non implica la violazione di copyright!) e anche l’accesso alla stessa Internet.<br />In realtà, siamo proprio \"un pezzo\" di Internet, poiché siamo un <a href=\"http://it.wikipedia.org/wiki/Sistema_autonomo\" target=\"_blank\" title=\"Richiede inoltro ad Internet\">Autonomous System</a> alla pari di Telecom, Fastweb e Google. Più precisamente siamo l’<a href=\"http://www.db.ripe.net/whois?searchtext=ninux&amp;searchSubmit=search\" target=\"_blank\" title=\"Richiede inoltro ad Internet\">Autonomous System n° <code>197835</code></a>.</p>
<br />
<h1>Come è fatta la nostra Rete</h1>
<p>Immaginiamo dei pc collegati tra loro da un cavo ethernet. Ora spostiamoli tra loro a distanze di centinaia di metri l\'uno dall\'altro, ognuno in una rispettiva abitazione. Ora, sostituiamo il cavo di rete, che dovrebbe essere molto lungo e costoso, con un dispositivo wireless.<br />In sintesi, la nostra Rete segue questo tipo di criterio.</p>
<p>Gli ingredienti alla base della nostra Rete sono principalmente quattro: l\'hardware, il software, i protocolli di routing, e le persone.</p>
<br />
<h2>Hardware</h2>
<p>Il mercato offre diversi tipi di dispositivi wireless, che sono da valutare secondo il caso. Principalmente i dispositivi che utilizziamo di più appartengono alla <a href=\"http://www.ubnt.com/\" target=\"_blank\" title=\"Richiede inoltro ad Internet\">Ubiquiti Networks, Inc.</a> perché offre soluzioni performanti ad un costo accessibile. Inoltre i dispositivi sono ben prodotti e presentano buona tollerabilità di caldo, freddo ed eventi atmosferici. Infine garantiscono una discreta banda (fino a 180Mbps teorici, grazie al firmware proprietario), una distanza massima di circa 15 km e offrono una buona facilità di puntamento.</p>
<p>Per poter effettuare un collegamento però, è necessario che i dispositivi si \"vedano\", cioè che non abbiano ostacoli tra loro. Un esempio utile può essere un telecomando con la televisione: più ostacoli ci sono più rimane difficile cambiare canale... Questo è il motivo per cui montiamo pali sui tetti delle case!</p>
<p>Quando su un nodo vengono montati diversi apparati lo chiamiamo <i>supernode</i>, mentre un nodo che ne conta uno solo lo chiamiamo <i>nodo foglia</i>.</p>
<p><b>Note riguardo all\'affidabilità dei nostri impianti</b><br />Poiché svolgiamo questa attività nel tempo libero, è per noi importante limitare le manutenzioni agli impianti, sopratutto se abbiamo di fronte dei <i>supernode</i> perché costituiscono la <a href=\"http://it.wikipedia.org/wiki/Dorsale_(informatica)\" target=\"_blank\" title=\"Richiede inoltro ad Internet\">dorsale</a> della Rete e sono fondamentali per la \"sopravvivenza\" di alcune zone verso la quale sono connesse.</p>
<br />
<h2>Software</h2>
<p>Possiamo considerare ogni dispositivo come se fosse un \"mini-computer\" dotato di un antenna. Proprio come un pc, ogni dispositivo ha bisogno per funzionare di un Sistema Operativo con la differenza però che hanno molta poca memoria a disposizione. I Sistemi Operativi che permettono il funzionamento di questi apparati si chiamano <a href=\"http://it.wikipedia.org/wiki/Firmware\" target=\"_blank\" title=\"Richiede inoltro ad Internet\">firmware</a> e devono essere fatti <i>ad hoc</i>.</p>
<p>Sui nostri nodi, i dispositivi hanno il firware <a href=\"https://github.com/ninuxorg/ninux-airos-fw-oldstable\" target=\"_blank\" title=\"Richiede inoltro ad Internet\">Ubiquiti AirOS<a> modificato da noi, oppure <a href=\"https://openwrt.org/\" target=\"_blank\" title=\"Richiede inoltro ad Internet\">Openwrt</a>. Il primo, che è comunque basato su OpenWRT, ha il vantaggio di realizzare collegamenti molto stabili e performanti grazie ad estensioni proprietarie dei driver, mentre il secondo ha il vantaggio di essere totalmente aperto e non legato soltato agli apparati di un singolo produttore. Tra i programmi che sono installati su questi apparati, uno di questi è il demone di routing. Mai sentito nominare? Andiamo avanti.</p>
<br />
<h2>Protocolli di routing</h2>
<p>In informatica un protocollo è la lingua che una specifica applicazione sa parlare per poter comunicare con il resto. Nel nostro caso si chiama <acronym title=\"Internet Protocol\">IP</acronym> e prevede che ogni nodo abbia un indirizzo univoco all’interno della rete, in modo da non essere riutilizzato per altri dispositivi, l’indirizzo IP appunto.<br />Così, ogni dispositivo ha un programma, detto <i>demone di routing</i>, responsabile di far conoscere a tutti gli altri nodi il proprio indirizzo, di trovare i percorsi più brevi per instradare i dati all\'interno della rete popolando le <i>tabelle di routing</i> che servono a qualunque dispositivo per sapere su che collegamento fisico inviare i dati.<br />In questo modo, ogni nodo conosce il percorso che devono fare i suoi dati per parlare con qualunque altro nodo della Rete Ninux, e con le reti a cui quest\'ultima è connessa, tra cui ad esempio Internet stessa.</p>
<p>I demoni di routing parlano un <i>protocollo di routing</i>, che nel nostro caso si chiama <a href=\"http://olsr.org/\" target=\"_blank\" title=\"Richiede inoltro ad Internet\">OLSR</a>.<br />La peculiarità di OLSR è che si accorge automaticamente di quando un collegamento cade o degrada la sua capacità di comunicare (ad esempio per un interruzine elettrica), e reimposta i percorsi all’interno della rete affinché il flusso di dati faccia sempre il percorso migliore (più corto e di migliore qualità).</p>